services:
  my_app:
    build: .
    container_name: flask_app
    ports:
      - 80:80
    networks:
      - eminnet
    depends_on:
      - database
    restart: always
  database:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    networks:
      - eminnet
    volumes:
      - eminvol:/var/lib/mysql
networks:
  eminnet:
volumes:
  eminvol: 
